# Generated by Django 3.2 on 2023-02-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230216_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Anonym', 'Аноним'), ('user', 'Аутентифицированный пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор'), ('superuser', 'Суперюзер')], default='USER_ROLE_USER', max_length=30, verbose_name='Роль'),
        ),
    ]
