# Generated by Django 3.2 on 2023-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Anonym', 'Аноним'), ('USER_ROLE_USER', 'Аутентифицированный пользователь'), ('USER_ROLE_MODERATOR', 'Модератор'), ('USER_ROLE_ADMIN', 'Администратор'), ('superuser', 'Суперюзер')], default='USER_ROLE_USER', max_length=30, verbose_name='Роль'),
        ),
    ]
