# Generated by Django 3.2 on 2023-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER_ROLE_USER', 'Аутентифицированный пользователь'), ('USER_ROLE_MODERATOR', 'Модератор'), ('USER_ROLE_ADMIN', 'Администратор')], default='user', max_length=30, verbose_name='Роль'),
        ),
    ]
