version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    # build: ../api_yamdb/
    image: yoxyyyy/yamdb_final:latest
    restart: always
    command: sh -c "cd api_yamdb/ &&
                gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "82:82"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/../api_yamdb/templates:/var/html/redoc/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  data_value:
  static_value:
  media_value:
  