# Generated by Django 3.2 on 2023-05-09 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230225_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default='1', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальный рейтинг - 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Максимальный рейтинг - 10')]),
        ),
    ]
